interface GuideInput {
  summary: string
  useWhen: string[]
  steps: string[]
  example: string
  effects: string[]
  watchFor: string[]
  links?: Array<{ label: string; route: string }>
}

function guide(input: GuideInput): string {
  const section = (heading: string, items: string[], ordered = false) =>
    `## ${heading}\n\n${items.map((item, index) => ordered ? `${index + 1}. ${item}` : `- ${item}`).join('\n')}`
  const links = input.links?.length
    ? `\n\n${input.links.map((link) => `[Open ${link.label} →](${link.route})`).join('  \n')}`
    : ''

  return [
    input.summary,
    section('Use this when', input.useWhen),
    section('How to use it', input.steps, true),
    `## Practical example\n\n> ${input.example}`,
    section('What happens next', input.effects),
    section('Watch for', input.watchFor),
  ].join('\n\n') + links
}

export const EXPANDED_HELP_GUIDES: Record<string, string> = {
  'navigating-the-app': guide({
    summary: 'CrewBarn groups daily work in the main navigation and tenant setup in the Tool Shed. What appears depends on the signed-in user’s role, enabled modules, and tenant configuration.',
    useWhen: ['You are learning where a function lives.', 'A coworker can see a page that you cannot.', 'You need to move between a list, record detail, and its related setup.'],
    steps: ['Use the main navigation for operational work such as Customers, Jobs, Estimates, Inventory, and Accounting.', 'Open a row or card to reach a record’s detail page; use its tabs for related history, files, messages, and activity.', 'Open **Tool Shed** for company setup, workflows, roles, integrations, and business controls.', 'Use Help search for a feature name, or press **?** to open the guide for the current settings page.', 'If a function is missing, check the tenant’s Modules setting and ask an owner to verify your role permissions.'],
    example: 'A dispatcher works in Jobs and Customers all day, but opens Tool Shed → Job Statuses only when changing workflow rules or customer notifications.',
    effects: ['Navigation does not grant access; API permissions still enforce every protected action.', 'Layout and density preferences can change where navigation appears without changing the underlying functions.'],
    watchFor: ['Do not share an owner login to work around missing access. Give the person an appropriate role instead.', 'A hidden module and a denied permission can look similar; check both.'],
    links: [{ label: 'Tool Shed', route: '/tool-shed' }, { label: 'App Layout', route: '/tool-shed/appearance' }],
  }),
  'help-and-feedback': guide({
    summary: 'CrewBarn Help provides searchable instructions and direct links. CBI can answer questions using the page you are viewing, while support and tester notes are better for defects or product feedback.',
    useWhen: ['You need instructions for a feature.', 'You need CBI to explain the current screen or record.', 'Something behaves differently from the documented workflow.'],
    steps: ['Press **?** or use the header Help button.', 'Search by the function name, business task, or field label.', 'Use a topic’s **Open** button to go directly to the function.', 'Enable the floating CBI button when you want page-aware AI help.', 'For a defect, record what you expected, what happened, the record involved, and the exact error message before contacting support.'],
    example: 'If a status refuses to move to Complete, open the Job Statuses guide first. If the selected flow requirements are satisfied but the API still rejects it, send support the job number, current status, target status, and error text.',
    effects: ['Opening Help does not change data.', 'CBI access and allowed actions still follow tenant AI settings and the signed-in user’s permissions.'],
    watchFor: ['Do not include customer passwords, API secrets, or encryption keys in feedback.', 'Screenshots are useful, but include the workflow and record identifier so the issue can be reproduced.'],
  }),
  'creating-a-customer': guide({
    summary: 'A customer is the account your company serves and usually bills. Contacts are people; service locations are the physical places where work happens.',
    useWhen: ['A new person or company requests service.', 'An existing corporate customer adds a new branch.', 'You need a billing account before creating an estimate or job.'],
    steps: ['Open **Customers** and choose **New customer**.', 'Choose the correct customer type and enter the account or household name.', 'Add the primary contact’s phone and email; mark billing or main-contact responsibility when applicable.', 'Add the billing address and at least one service location if work will occur at a different place.', 'Review payment terms, tax treatment, parent customer, tags, and custom fields.', 'Save, then create the first estimate, job, asset, or note from the customer record.'],
    example: 'Create “Harbor Property Management” as the billing customer, add its accounting manager as billing contact, then add “Bay Street Apartments” as a service location where technicians actually work.',
    effects: ['Jobs, estimates, invoices, communications, assets, and service history can all connect to this customer.', 'The selected billing contact and billing customer affect where customer documents and balances go.'],
    watchFor: ['Search before creating a customer to avoid duplicate accounts.', 'Do not put a branch address in the contact fields; create a service location.', 'Confirm SMS and email consent before sending customer communication.'],
    links: [{ label: 'Customers', route: '/customers' }, { label: 'Customer Types', route: '/tool-shed/customer-types' }],
  }),
  'contacts-vs-service-locations': guide({
    summary: 'Contacts answer “who do we speak to?” Service locations answer “where does the technician go?” Keeping them separate prevents incorrect dispatching, communication, and asset history.',
    useWhen: ['A customer has multiple people or phone numbers.', 'Billing happens at one address while service happens elsewhere.', 'A commercial account has several branches or buildings.'],
    steps: ['Add each person as a contact with their own phone, email, and responsibility.', 'Mark the appropriate main and billing contacts instead of copying details into notes.', 'Create one service location for each physical site where work or assets exist.', 'Store access instructions, gate codes, and location-specific fields on the service location.', 'Choose the correct contact and location when creating each job or estimate.'],
    example: 'The corporate office manager is the billing contact, the building engineer is the on-site contact, and each building is a separate service location under the same customer.',
    effects: ['Dispatch, maps, territories, and field arrival use the service location.', 'Email, SMS, estimates, and invoices use the selected customer/contact rules.', 'Customer assets stay with their physical service location.'],
    watchFor: ['Moving an address between customer and location fields can break reporting assumptions.', 'Do not create a new customer for every address when one organization owns all locations unless billing truly needs separate accounts.'],
  }),
  'parent-customer': guide({
    summary: 'Parent and child customers model organizations where separate branches or entities roll up to a headquarters or payer while keeping their own service history.',
    useWhen: ['Headquarters pays invoices for branch offices.', 'A property manager or franchise needs roll-up reporting.', 'Locations must remain separate customer accounts for contacts, terms, or reporting.'],
    steps: ['Create or identify the top-level parent customer.', 'Open the child customer and select the parent in the customer relationship field.', 'Confirm whether jobs at the child should default billing to the parent.', 'Review contacts, payment terms, tax settings, and service locations on both records.', 'Test with a draft estimate or job and confirm the service customer and billing customer are correct.'],
    example: '“Acme Corporate” is the parent; “Acme Orlando Branch” is the service customer. The branch owns the location and assets, while invoices default to corporate accounting.',
    effects: ['Service history remains on the child while supported reports can roll up to the parent.', 'Billing can default to the parent but remains overridable per job.'],
    watchFor: ['Do not create circular parent relationships.', 'Changing a parent does not automatically rewrite historical invoices.', 'Confirm the billing contact exists on the account that will receive documents.'],
  }),
  'job-billing-override': guide({
    summary: 'A job can serve one customer while billing another. This keeps field history attached to the correct site without sending the invoice to the wrong payer.',
    useWhen: ['A parent company pays for a branch.', 'A landlord, property manager, warranty provider, or third party pays for service.', 'The service location and accounts-receivable customer differ.'],
    steps: ['Create or open the job.', 'Keep the service customer and service location set to where work is performed.', 'Choose the separate billing customer in the billing section.', 'Confirm the billing contact, payment terms, tax behavior, and customer-facing document address.', 'Preview the estimate or invoice before sending it.'],
    example: 'A technician repairs equipment at “Tenant Store 14,” but “National Facilities LLC” is selected as billing customer and receives the invoice.',
    effects: ['Assets and job history follow the service customer/location.', 'Invoices, balances, and accounts-receivable reporting follow the billing customer.'],
    watchFor: ['Changing the billing customer after documents or payments exist may require accounting review.', 'Do not use a note as a substitute for the billing-customer field.'],
  }),
  'what-is-an-asset': guide({
    summary: 'A customer asset is a specific physical item your company services over time, such as an HVAC unit, lock, extinguisher, panel, safe, door, or piece of equipment. It belongs to a customer service location and keeps its identity across many jobs.',
    useWhen: ['Technicians need history for the exact unit they are servicing.', 'Serial numbers, model details, photos, documents, warranties, or installed parts must follow the equipment.', 'A QR label should open the right service record in the field.'],
    steps: ['Open **Customer Assets** and choose **New asset**, or add one from a customer/service-location record.', 'Select the customer, exact service location, and asset type.', 'Enter the identifying name, manufacturer, model, serial number, install date, and location details that your trade needs.', 'Attach clear identification photos, manuals, inspection documents, or warranty information.', 'Print and attach the asset’s QR label when field scanning is part of the workflow.', 'On jobs, select the assets covered by the visit so work, parts, photos, and history connect to the right equipment.'],
    example: 'Create “RTU-3” at the customer’s North Building with model and serial number, attach the nameplate photo and manual, then cover RTU-3 on the maintenance job. The next technician can scan its label and see prior service and installed components.',
    effects: ['Covered-job history becomes visible on the asset.', 'Installed serialized parts can move from inventory into the asset’s component history.', 'QR scans resolve to this asset while access rules control how much the viewer sees.'],
    watchFor: ['Search by serial number and location before adding an asset to avoid duplicates.', 'Do not use one asset record for multiple physical units.', 'Move the asset carefully if its service location changes so history stays intact.'],
    links: [{ label: 'Customer Assets', route: '/assets' }, { label: 'Asset Types', route: '/asset-types' }],
  }),
  'creating-an-asset': guide({
    summary: 'The New Asset wizard connects one physical unit to the correct customer and service location. Careful setup makes every later job, inspection, label, document, and installed component easier to trust.',
    useWhen: ['Adding equipment already installed at a customer site.', 'Commissioning newly installed equipment.', 'Creating the equipment record before quoting, inspecting, or servicing it.'],
    steps: ['Open **Customer Assets** and choose **New asset**.', 'Select the existing customer; create one only after searching for duplicates.', 'Select the exact service location where the unit is installed.', 'Choose the most specific optional group, such as Building → Floor → Room.', 'Enter a unique name, type, manufacturer, model, serial number, install date, inspection cadence, notes, and required custom fields.', 'Finish setup with an identification photo, QR label, documents, and serialized components when applicable.', 'Resolve report-readiness warnings before relying on the record in the field.'],
    example: 'Create “RTU-3” under Harbor Center → North Building → Roof → Zone 3. Record its model, serial, quarterly cadence, nameplate photo, manual, QR label, and installed controller serial.',
    effects: ['The service location and group establish where the asset belongs.', 'Inspection cadence can inherit from the asset type unless overridden.', 'Jobs, estimates, inspections, files, and component movements build one continuing history.'],
    watchFor: ['Search by serial and location first.', 'Create one record per physical unit.', 'Existing asset editing preserves the original service location, so choose it carefully during creation.'],
    links: [{ label: 'Customer Assets', route: '/assets' }, { label: 'Asset Types', route: '/asset-types' }],
  }),
  'asset-locations-groups': guide({
    summary: 'A service location identifies the customer site. Asset groups describe the physical structure inside that site, such as building, floor, wing, room, roof area, or production line.',
    useWhen: ['A site has several buildings or areas.', 'Technicians need a precise path to find equipment.', 'You need tree views, group filters, or batch labels.'],
    steps: ['Verify the correct customer and service location.', 'Open the group manager for that location.', 'Create a hierarchy from broad to specific, such as Building → Floor → Room.', 'Assign each asset to the most specific useful group.', 'Verify placement in tree view and with group filters.', 'Print batch labels only after checking the selected group and descendants.', 'Rename or remove groups only after reviewing every affected asset.'],
    example: 'At Central Hospital, place the air handler under Main Building → Floor 3 → Mechanical Room. “HVAC” belongs in Asset Type, not in the physical location tree.',
    effects: ['A parent group filter can include assets in child groups.', 'Tree view and batch printing follow the hierarchy.', 'Report readiness can warn when a required group is missing.'],
    watchFor: ['Groups belong to one service location.', 'Do not use groups as statuses or types.', 'Removing a group can leave its assets ungrouped.'],
    links: [{ label: 'Customer Assets', route: '/assets' }],
  }),
  'asset-inspections-reports': guide({
    summary: 'Inspection cadence defines how often an asset should be inspected. A completed inspection record and report prove what was actually checked; cadence alone is only the schedule.',
    useWhen: ['Equipment requires recurring compliance or preventive inspections.', 'Asset types need standard inspection frequencies.', 'A customer or authority needs a report tied to exact equipment.'],
    steps: ['Set the normal cadence on the asset type.', 'During asset creation, inherit that default or enter an asset-specific override.', 'Resolve identity and report-readiness warnings before the visit.', 'Select the exact covered assets on the inspection job.', 'Complete and finalize results for each asset.', 'Confirm the inspection and generated report in asset history.', 'Use cadence and the last completed inspection to plan the next visit.'],
    example: 'Fire Extinguisher defaults to annual inspection, while one special-site unit is overridden to quarterly. Each completed quarterly visit remains separate evidence.',
    effects: ['Type defaults make new setup consistent.', 'Finalized inspections remain separate historical events.', 'Reports combine asset identity, results, and related job information.'],
    watchFor: ['Cadence is not proof of completion.', 'Missing serial, type, location, or evidence reduces report quality.', 'Do not assume changing a type default rewrites existing assets.'],
    links: [{ label: 'Customer Assets', route: '/assets' }, { label: 'Asset Types', route: '/asset-types' }],
  }),
  'asset-components-inventory': guide({
    summary: 'An installed component connects an exact serialized inventory unit to the asset where it is installed. CrewBarn records custody instead of storing only a free-text part note.',
    useWhen: ['Installing a serialized controller, board, motor, lock core, or tracked unit.', 'Warranty or recall work requires the installed serial.', 'The office must know whether a unit is available, installed, or returned.'],
    steps: ['Confirm the product is serialized and the exact inventory unit is available.', 'Open the asset **Components** area.', 'Search by serial, SKU, or notes and select the exact unit.', 'Confirm installation and verify the component and movement in history.', 'When removed, record the return instead of deleting the component.', 'If it changes warehouse, truck, or bin, record that transfer separately.'],
    example: 'Install controller CTL-8842 on RTU-3. It moves from available stock to installed and records the asset, customer, and location. Removal creates a return event; a later transfer records its bin.',
    effects: ['The inventory unit changes from available to installed.', 'Install and return movements remain auditable.', 'Removal preserves its stock location until a separate movement changes it.'],
    watchFor: ['Unavailable units cannot be installed twice.', 'Free-text components weaken serial custody.', 'Non-serialized quantity usage belongs in normal job and stock consumption.'],
    links: [{ label: 'Customer Assets', route: '/assets' }, { label: 'Inventory Units', route: '/inventory?tab=units' }, { label: 'Inventory Settings', route: '/inventory?tab=settings' }],
  }),
  'asset-history-work': guide({
    summary: 'Asset history combines work explicitly linked to one physical unit: estimate lines, job lines, inspections, and serialized component installs or returns.',
    useWhen: ['Diagnosing repeat failures.', 'Checking prior recommendations or repairs.', 'Proving maintenance, inspection, or component history.'],
    steps: ['Verify the asset customer, location, model, and serial.', 'Review estimate events for proposed work.', 'Review job events for active or completed service.', 'Review inspections and reports.', 'Review component install and return movements.', 'Select the covered asset whenever creating new work.', 'Correct missing linkage at the source record instead of adding a duplicate summary.'],
    example: 'RTU-3 shows a motor recommendation, the approved replacement job, a completed inspection, and the installed motor serial. The next technician sees the repair without searching unrelated notes.',
    effects: ['History is newest first and links to source records.', 'Only explicitly linked work is reliably asset-specific.', 'Source metadata remains available for audit.'],
    watchFor: ['Choose the correct covered asset on every job.', 'Do not merge identical units into one record.', 'Empty history can mean missing linkage, not no prior work.'],
    links: [{ label: 'Customer Assets', route: '/assets' }, { label: 'Jobs', route: '/jobs' }, { label: 'Estimates', route: '/estimates' }],
  }),
  'asset-corrections-retirement': guide({
    summary: 'Preserve the identity of the physical unit. A typo correction, equipment replacement, duplicate, relocation, and retirement are different operations and should not overwrite history carelessly.',
    useWhen: ['Identity data is incorrect.', 'Old equipment is replaced.', 'Two records appear to be duplicates.', 'Equipment is retired or relocated.'],
    steps: ['For a typo, edit only the incorrect field.', 'Before retirement, record final condition, removal work, files, and component returns.', 'Create a new asset for a new physical unit, even in the same position.', 'Link new work to the replacement and retain the old history.', 'Compare serials, labels, history, files, and components before resolving duplicates.', 'Use the supported relocation process because normal editing preserves the original location.', 'Remove or reprint QR labels after identity or placement changes.'],
    example: 'When RTU-3 is replaced, retain the old record and removal history, then create the replacement with its own serial, install date, photos, and label. Never overwrite the old serial.',
    effects: ['Separate records preserve warranty and service evidence.', 'Editing a serial changes the identity shown across its history.', 'Component returns preserve custody before reuse.'],
    watchFor: ['Do not delete compliance or financial evidence.', 'Never move an old QR sticker to replacement equipment.', 'Return installed components before retirement.'],
    links: [{ label: 'Customer Assets', route: '/assets' }],
  }),
  'customer-vs-company-assets': guide({
    summary: 'Customer assets are equipment serviced at customer locations. Company assets are your own tools and equipment. Inventory is stock intended for sale, use, transfer, or installation.',
    useWhen: ['Deciding where a physical item belongs.', 'Tracking technician custody of company tools.', 'Separating installed equipment from warehouse or truck stock.'],
    steps: ['Identify who owns the item and why it is tracked.', 'Use **Customer Assets** for customer-site units needing service history, inspections, files, or QR records.', 'Use **Company Assets** for internal meters, machines, ladders, devices, and tools.', 'Use **Inventory** for products and serialized units held in warehouses, trucks, bins, or purchasing.', 'Record a serialized inventory unit as a component when installed into a customer asset.', 'Review accounting and custody steps before changing ownership.'],
    example: 'A customer alarm panel is a customer asset. A technician test meter is a company asset. A replacement board is inventory until installed as a component of the panel.',
    effects: ['Customer history stays separate from internal tool custody.', 'Inventory movements show where stock resides.', 'Installed serialized components connect stock custody to customer equipment.'],
    watchFor: ['Do not put company tools under customers.', 'Do not create uninstalled stock as customer assets.', 'Ownership transfers may require more than changing a category.'],
    links: [{ label: 'Customer Assets', route: '/assets' }, { label: 'Company Assets', route: '/company-assets' }, { label: 'Inventory', route: '/inventory' }],
  }),
  'asset-types': guide({
    summary: 'Asset types are the tenant’s reusable classification of customer equipment. They make asset lists, forms, reporting, and field terminology match the trade.',
    useWhen: ['The default asset choices do not match your business.', 'Different equipment needs separate reporting or identification.', 'Staff need consistent names instead of free-text variations.'],
    steps: ['Open **Asset Types**.', 'Review existing types and search for an equivalent before creating another.', 'Add a clear singular name used by technicians and office staff.', 'Activate the type and use it on a test asset.', 'Deactivate obsolete types only after checking existing asset usage.'],
    example: 'A fire-safety tenant creates Fire Extinguisher, Exit Light, Sprinkler Riser, and Fire Alarm Panel instead of storing everything as “Equipment.”',
    effects: ['New and edited assets can be classified with the type.', 'Filters and reports can separate service history by equipment class.'],
    watchFor: ['Renaming a type changes how existing assets are labeled.', 'Avoid types that are really locations, statuses, or temporary conditions.'],
    links: [{ label: 'Asset Types', route: '/asset-types' }],
  }),
  'asset-photos-documents': guide({
    summary: 'Asset media preserves identification, condition, instructions, compliance records, and reference material beyond a single job.',
    useWhen: ['A technician needs a nameplate, wiring, lock, or installation reference.', 'Manuals, certificates, inspection reports, or warranties must remain with the equipment.', 'Before/after condition should be available on future visits.'],
    steps: ['Open the asset detail.', 'Upload an identification photo first, including serial/model plates when useful.', 'Add supporting photos with enough context to understand orientation and condition.', 'Upload manuals, certificates, warranty files, or prior reports as documents.', 'Use clear file names and verify the preview opens before leaving the record.'],
    example: 'For an alarm panel, upload a full cabinet photo, a readable model/serial label, the zone diagram, and the manufacturer manual.',
    effects: ['Authorized office and field users can access the files from the asset.', 'Files remain with the asset across future jobs.'],
    watchFor: ['Do not upload customer secrets or unrelated personal documents.', 'Job-specific proof may also belong on the job; asset files should remain useful over time.'],
  }),
  'qr-labels': guide({
    summary: 'Asset QR labels give the physical item a durable link to its CrewBarn record so field staff can identify it without searching by customer, model, or serial number.',
    useWhen: ['Many similar assets exist at one location.', 'Technicians need fast access to service history.', 'Customers or inspectors may use the public scan experience.'],
    steps: ['Open an asset and verify its name, location, and identifying details.', 'Choose **Print label** for one asset or use batch printing from the asset list.', 'Select the correct label stock and confirm print scaling is 100%.', 'Attach the label where it is readable but protected from heat, weather, cleaning, or moving parts.', 'Scan the installed label with a phone before leaving to confirm it opens the correct asset.'],
    example: 'Print labels for every extinguisher in a building, attach each to its matching unit, then scan all labels during commissioning to catch swapped records.',
    effects: ['The QR code continues to point to the same asset record as history grows.', 'Logged-in and public viewers see different information based on access.'],
    watchFor: ['Never attach a label without test-scanning it.', 'Replacing an asset may require a new asset record rather than moving the old label to new equipment.'],
  }),
  'public-scan': guide({
    summary: 'The public scan flow lets a phone open a limited asset page without exposing private tenant data. Signed-in users can receive a richer experience according to their permissions.',
    useWhen: ['A customer, inspector, or unknown scanner opens an asset QR code.', 'A technician scans a label from outside the app.', 'Someone requests access to additional asset information.'],
    steps: ['Scan the QR code with the phone camera.', 'If prompted, sign in to receive the tenant-authorized view.', 'Review the asset identity before recording or requesting anything.', 'Anonymous users can use the available access-request flow when more information is needed.', 'Authorized staff review requests in **Asset Access Requests** and approve only the appropriate person and scope.'],
    example: 'A building manager scans an extinguisher label and sees its public identity and service status, then requests access; office staff verify the requester before approval.',
    effects: ['Public viewers receive a sanitized view.', 'Access requests create a reviewable tenant workflow rather than automatically exposing records.'],
    watchFor: ['Do not place private notes, credentials, or sensitive customer information in public-facing fields.', 'Verify the requester independently before granting access.'],
    links: [{ label: 'Asset Access Requests', route: '/asset-access-requests' }],
  }),
  'service-vs-product-items': guide({
    summary: 'Service catalog items describe labor or work sold. Product catalog items describe physical goods and can participate in purchasing, stock, serialization, job usage, and asset installation.',
    useWhen: ['Building estimate and job line-item choices.', 'Deciding whether an item should affect inventory.', 'Standardizing price, cost, tax, and descriptions.'],
    steps: ['Use **Service Catalog** for labor, inspections, flat-rate tasks, and non-stock work.', 'Use **Product Catalog** for parts, materials, equipment, or merchandise.', 'Set the customer-facing name and description.', 'Configure price, cost, category, tax class, and active status.', 'For products, decide whether the item is stocked, serialized, reorderable, or installable on assets.', 'Add each item to a test estimate/job and verify pricing and tax.'],
    example: '“Annual Fire Inspection” is a service; “5 lb ABC Extinguisher” is a product that can be received into a warehouse, moved to a truck, and installed at a customer.',
    effects: ['Catalog defaults prefill transaction lines but authorized staff may be able to override values.', 'Stocked products create inventory movements when received, transferred, used, or adjusted.'],
    watchFor: ['Do not mark labor as stocked.', 'Changing price or tax defaults does not necessarily rewrite historical documents.', 'Duplicate catalog items make reporting and stock control unreliable.'],
    links: [{ label: 'Service Catalog', route: '/catalog/services' }, { label: 'Product Catalog', route: '/catalog/products' }],
  }),
  'catalog-categories': guide({
    summary: 'Catalog categories organize services and products into predictable trees for pickers, maintenance, and reporting. Service and product categories remain separate.',
    useWhen: ['Catalog lists are difficult to search.', 'Different teams need consistent groups.', 'Reporting should roll related offerings together.'],
    steps: ['Open the service or product category manager.', 'Design a small, understandable hierarchy before adding many levels.', 'Create parent categories first, then child categories.', 'Assign catalog items to the most specific useful category.', 'Test the category in estimate/job pickers and adjust names that staff misinterpret.'],
    example: 'Door Hardware contains Cylinders, Deadbolts, and Exit Devices, while Locksmith Services contains Rekey, Lockout, and Master Key work.',
    effects: ['Catalog pickers and filters use the category structure.', 'Moving a category can change where many items appear.'],
    watchFor: ['Avoid a separate category for every item.', 'Do not mix products and services into the wrong category tree.', 'Deactivate or reorganize carefully when active documents depend on familiar navigation.'],
  }),
  'tax-classes': guide({
    summary: 'Tax classes are reusable tax rules assigned to catalog items and transaction lines. Components support combined state, county, city, or special-purpose rates.',
    useWhen: ['Different products or services have different tax treatment.', 'A jurisdiction combines multiple rates.', 'The company needs consistent tax calculations.'],
    steps: ['Confirm the required tax treatment with the company’s tax professional.', 'Open **Tax Classes** and create a clear class name.', 'Add each required component and rate.', 'Assign the class to the correct catalog items.', 'Create a test estimate or invoice and verify subtotal, taxable amount, and each tax component.', 'Keep evidence of why the rate changed and the effective date.'],
    example: 'A taxable hardware class combines 6% state tax and 1% local tax, while inspection labor uses a non-taxable class according to the tenant’s jurisdiction.',
    effects: ['Assigned items use the class when added to supported documents.', 'Changes can affect future calculations and should be reviewed before customer use.'],
    watchFor: ['CrewBarn applies configured rules but does not replace tax advice.', 'Do not change a live rate without checking historical-document behavior and effective-date requirements.'],
    links: [{ label: 'Tax Classes', route: '/catalog/tax-classes' }],
  }),
  'locations-vs-bins': guide({
    summary: 'An inventory location is a warehouse, truck, shop, returns area, or other stock-holding place. Bins are the exact shelves, drawers, cages, or staging areas inside that location.',
    useWhen: ['Setting up warehouses and service vehicles.', 'Staff need to know the exact place to pick or return a part.', 'Stock totals are correct overall but difficult to locate physically.'],
    steps: ['Create each real stock-holding location with the correct type and active state.', 'Assign mobile locations or trucks to the appropriate technician when supported.', 'Create bins that match physical labels such as Shelf A1 or Drawer 3.', 'Label the physical bin to match CrewBarn.', 'Receive, transfer, and adjust stock at the bin level.', 'Deactivate obsolete bins only after moving or reconciling their stock.'],
    example: 'Melbourne Shop is the location; Receiving, Shelf A1, and Returns are bins. Truck 4 is another location with Cab, Drawer 1, and Drawer 2 bins.',
    effects: ['Stock levels are tracked at the bin level and roll up to locations.', 'Transfers and movements preserve source and destination history.'],
    watchFor: ['Do not use one generic bin for an entire warehouse if staff need reliable picking.', 'Never delete or deactivate a stock-holding place before accounting for its quantity.'],
    links: [{ label: 'Inventory', route: '/inventory' }],
  }),
  'transferring-stock': guide({
    summary: 'A transfer moves on-hand stock between bins without buying, selling, or consuming it. It is the normal way to load trucks, return unused parts, or reorganize a warehouse.',
    useWhen: ['Loading a technician’s truck.', 'Returning parts from a job or truck.', 'Moving products between warehouse shelves or locations.'],
    steps: ['Open Inventory and choose the transfer function.', 'Select the exact source bin and destination bin.', 'Add each product and quantity; scan serialized units individually when required.', 'Review available quantity and verify source/destination are not reversed.', 'Submit the transfer once.', 'Confirm the destination stock level and movement rows.'],
    example: 'Move ten keyed cylinders from Warehouse Shelf A1 to Truck 4 Drawer 2 before the morning route; each product creates an auditable movement.',
    effects: ['The source decreases and destination increases by the same quantity.', 'Serialized units change custody/location without losing identity.'],
    watchFor: ['A transfer is not a purchase receipt or a job usage transaction.', 'Do not repeat submission if the screen is slow; check movements first.', 'Scan requirements in Inventory Settings may block manual selection.'],
  }),
  'movements-log': guide({
    summary: 'The inventory movement log is the audit trail for every quantity change, including receipts, transfers, job usage, returns, reconciliation, and manual adjustments.',
    useWhen: ['A stock count does not match expectation.', 'You need to trace who moved or used a part.', 'Accounting or management needs the source transaction.'],
    steps: ['Open Inventory → Movements.', 'Filter by date, item, location, bin, movement type, job, purchase order, or user where available.', 'Open the relevant row and inspect source, destination, quantity, reference, timestamp, and actor.', 'Follow the linked job, PO, transfer, or reconciliation.', 'Correct the business transaction or create an authorized adjustment; do not edit history to hide the cause.'],
    example: 'A deadbolt is missing from Truck 4. The movement log shows it was pulled onto Job 1042 by a technician, explaining the stock decrease.',
    effects: ['Movements support auditability and rebuild the story behind current stock.', 'Corrections should create new traceable activity rather than erasing old activity.'],
    watchFor: ['A current stock total without movement context is not enough to diagnose discrepancies.', 'Check time zone, location, and similarly named bins before concluding a movement is wrong.'],
  }),
  'serialized-units': guide({
    summary: 'Serialized tracking follows one physical unit by serial number through receiving, storage, transfer, job use, installation, return, and retirement.',
    useWhen: ['Warranty, compliance, or customer history requires exact-unit identity.', 'High-value equipment must be traceable.', 'The same product model has many individual units.'],
    steps: ['Mark the product as serial-number tracked before receiving units.', 'Receive or register each unit with a unique, verified serial number.', 'Scan or select that exact unit during transfers.', 'On the job, record the exact unit used or installed.', 'Associate installation with a covered customer asset when applicable.', 'Use the Units view to verify current location and history.'],
    example: 'Receive three alarm panels of the same model with three serial numbers, move one to Truck 2, then install that exact unit on the customer’s panel asset.',
    effects: ['Quantity and unit identity stay linked.', 'Installed-unit history supports warranty and service investigation.'],
    watchFor: ['Do not reuse a serial number or type a placeholder.', 'Free-text installation can weaken traceability and should follow Inventory Settings.', 'Correct serial mistakes before downstream transfers or installation whenever possible.'],
  }),
  'reconciliations': guide({
    summary: 'Reconciliation compares physical counts with CrewBarn and records an approved explanation and adjustment for differences.',
    useWhen: ['Cycle counting a bin or truck.', 'A physical count differs from system quantity.', 'A manager needs to review recurring shrinkage or process failures.'],
    steps: ['Choose the location/bin and count stock physically without relying only on the displayed quantity.', 'Enter counted quantities and identify discrepancies.', 'Review recent movements, open jobs, transfers, and receipts before adjusting.', 'Select the appropriate resolution or reason.', 'Approve the reconciliation with the required permission.', 'Review the resulting movements and investigate repeated discrepancies.'],
    example: 'System quantity is five cylinders but the shelf contains three. Movement review finds no transaction, so an authorized adjustment records the shortage and reason.',
    effects: ['Approved differences create auditable inventory adjustments.', 'The new on-hand quantity reflects the accepted count.'],
    watchFor: ['Do not reconcile away an in-progress transfer or unposted job usage.', 'Large or repeated variances should be investigated, not merely accepted.'],
  }),
  'creating-a-po': guide({
    summary: 'A purchase order records what the tenant intends to buy from a vendor. Stock does not increase until items are received.',
    useWhen: ['Restocking products.', 'Ordering job-specific material.', 'Creating an approval and cost trail before inventory arrives.'],
    steps: ['Open Purchase Orders and choose **New**.', 'Select the correct vendor and destination expectations.', 'Add product lines, ordered quantities, unit costs, vendor references, and notes.', 'Review totals and duplicate open orders.', 'Save or place the order according to the available workflow.', 'Keep the PO open until each shipment is received or intentionally closed.'],
    example: 'Order twenty deadbolts and ten cylinders from the hardware distributor, with agreed unit costs and the vendor’s confirmation number.',
    effects: ['The PO tracks ordered, received, and remaining quantities.', 'No stock movement occurs until receiving.'],
    watchFor: ['Do not manually add stock just because a PO was placed.', 'Confirm units of measure and cost before ordering.', 'Avoid duplicate POs for the same shortage.'],
    links: [{ label: 'Purchase Orders', route: '/purchase-orders' }, { label: 'Vendors', route: '/vendors' }],
  }),
  'receiving-a-po': guide({
    summary: 'Receiving confirms that ordered goods physically arrived and places accepted quantity into a destination inventory bin.',
    useWhen: ['A full or partial vendor shipment arrives.', 'Serial numbers must be captured.', 'Actual quantity or condition differs from the order.'],
    steps: ['Open the matching purchase order; do not create a second receipt from memory.', 'Compare the shipment and packing slip to each PO line.', 'Choose the exact receiving location and bin.', 'Enter only the quantity physically accepted; capture required serial numbers.', 'Record shortages, damage, backorders, or notes.', 'Submit once and verify stock movements and remaining open quantity.'],
    example: 'A PO ordered ten panels, but six arrive. Receive six into Warehouse Receiving, record each serial number, and leave four open for the next shipment.',
    effects: ['Accepted quantity increases the destination bin.', 'Movement rows link inventory back to the PO and receipt.', 'Partial receiving preserves remaining quantities.'],
    watchFor: ['Do not receive damaged or missing goods as good stock.', 'Check whether the supplier shipped substitutions before assigning serials or products.', 'Avoid duplicate receiving if the page refreshes slowly.'],
  }),
  'needs-ordered': guide({
    summary: 'Needs Ordered identifies stocked products below their configured reorder point so purchasing can act before field operations run out.',
    useWhen: ['Preparing a regular replenishment order.', 'Reviewing low stock across warehouse and trucks.', 'Turning demand into vendor POs.'],
    steps: ['Set meaningful reorder thresholds on stocked products.', 'Open Purchase Orders → Needs Ordered.', 'Review current quantity, threshold, open POs, demand, and preferred vendor.', 'Combine appropriate items into vendor purchase orders.', 'Avoid ordering quantities already covered by open POs.', 'Review thresholds after seasonal or business changes.'],
    example: 'A cylinder drops to four with a reorder point of six. Purchasing sees an open PO for two, so it avoids creating a duplicate order.',
    effects: ['The report changes as stock, thresholds, and open purchasing change.', 'Creating a PO records intent but does not clear the shortage until the system’s calculation recognizes the order/receipt behavior.'],
    watchFor: ['A poor reorder threshold creates noise or stockouts.', 'Check stock spread across locations; total quantity may hide an empty truck.'],
  }),
  'what-is-a-job': guide({
    summary: 'A job, or work order, is the operational record for customer work. It brings together service location, schedule, assignment, status, field visits, line items, assets, communication, closeout, invoice, and payment context.',
    useWhen: ['Work has been approved or requested.', 'A technician must be scheduled and dispatched.', 'The office needs one record for field and financial history.'],
    steps: ['Create the job from a customer, approved estimate, request, or Jobs page.', 'Select the service customer, service location, billing customer, job type, and initial status.', 'Add scope, line items, covered assets, instructions, and required custom fields.', 'Schedule the visit and assign the lead technician/crew.', 'Use tenant-defined statuses and field check-in/out during execution.', 'Complete required photos, signatures, checklist, notes, parts, and visit closeout.', 'Review charges, invoice, collect payment, and preserve follow-up or warranty needs.'],
    example: 'An approved HVAC estimate becomes a job at Building A, assigned to a technician for Tuesday. The tech checks in, services RTU-3, records parts/photos/signature, checks out Complete, and the office invoices the billing customer.',
    effects: ['Status and schedule drive dispatch visibility.', 'Parts can create inventory movements and asset component history.', 'Triggers can send customer messages when statuses change.', 'Completion, invoicing, and payment are related but distinct stages.'],
    watchFor: ['Use the tenant’s statuses and rules; do not assume names have hard-coded meaning.', 'Verify service and billing customers before sending documents.', 'A physical field event may update status automatically according to tenant field-action mapping.'],
    links: [{ label: 'Jobs', route: '/jobs' }, { label: 'Job Statuses', route: '/tool-shed/job-statuses' }, { label: 'Job Types', route: '/tool-shed/job-types' }],
  }),
  'job-line-items': guide({
    summary: 'Job line items describe what is charged and, for stocked products, what physical material is used. Services and products have different inventory consequences.',
    useWhen: ['Building the job price.', 'Recording labor, flat-rate work, parts, or equipment.', 'Pulling a stocked or serialized item from a bin.'],
    steps: ['Open the job’s line-item section.', 'Add a service from the catalog for labor or work.', 'Add a product for material or equipment.', 'Confirm description, quantity, unit price, discount, tax, and billing visibility.', 'For stocked products, select the actual source bin and exact serialized unit when required.', 'Associate installed products with covered assets where applicable.', 'Review totals and inventory results before invoicing.'],
    example: 'Add one Rekey Service and six cylinders. The service affects price only; the cylinders are pulled from Truck 3 Drawer 1 and create inventory usage movements.',
    effects: ['Line values contribute to job and invoice totals.', 'Stocked product usage decreases the selected bin.', 'Installed serialized units can become asset components.'],
    watchFor: ['Do not use a service item to represent stock consumption.', 'Confirm quantities and source bins before closeout.', 'Changing a line after invoicing may require financial correction rather than simple editing.'],
  }),
  'covered-assets': guide({
    summary: 'Covered assets identify the exact customer equipment included in the job, connecting field work and installed parts to long-term asset history.',
    useWhen: ['A visit services one or more known assets.', 'Photos, notes, checklist results, or parts should be traceable to equipment.', 'The same location has many similar units.'],
    steps: ['Confirm the job has the correct customer and service location.', 'Open the covered-assets picker.', 'Select only the assets included in the current scope.', 'Add a missing asset with correct identifiers instead of choosing a similar unit.', 'During field work, associate relevant service results and installed parts.', 'Verify the asset history after closeout.'],
    example: 'A maintenance job at a building covers RTU-2 and RTU-3 but not RTU-1. A replacement motor is installed on RTU-3, preserving the correct equipment history.',
    effects: ['The job appears in each covered asset’s history.', 'Installed products may appear in the selected asset’s component history.'],
    watchFor: ['Do not select every asset at the location for convenience.', 'Serial and model details should distinguish similar units.', 'Removing an asset after recorded installation can break expected history.'],
  }),
  'creating-an-estimate': guide({
    summary: 'An estimate proposes scope, price, tax, and terms before work is authorized. It can later be sent for customer approval and converted into a job.',
    useWhen: ['The customer must approve price or scope.', 'Several options or revisions may be needed.', 'Work should not enter dispatch until accepted.'],
    steps: ['Open Estimates and choose **New**.', 'Select service customer, service location, billing customer, and contact.', 'Add clear scope and catalog line items.', 'Confirm quantities, prices, discounts, taxes, payment terms, notes, and expiration.', 'Preview customer-facing content.', 'Save as draft and have an authorized person review it before sending.'],
    example: 'Prepare an estimate for replacing two exit devices, including hardware, installation labor, tax, and a thirty-day validity period.',
    effects: ['Draft estimates can be revised before sending.', 'Approval can unlock conversion into a job.', 'Estimate activity becomes part of customer history.'],
    watchFor: ['Confirm the recipient and billing customer.', 'Do not send placeholder descriptions or internal notes.', 'Use revisions/superseding behavior rather than silently changing an accepted proposal.'],
    links: [{ label: 'Estimates', route: '/estimates' }],
  }),
  'sending-estimates': guide({
    summary: 'Sending delivers the customer-facing estimate and begins the approval workflow. Recipient selection follows the customer’s configured contact priorities.',
    useWhen: ['The draft has been reviewed and is ready for customer decision.', 'The customer needs a secure approval/rejection link.', 'The office needs a record of what was offered.'],
    steps: ['Open the draft estimate and review scope, price, tax, terms, expiration, branding, and attachments.', 'Verify the billing contact, then main contact, then fallback contact has the intended email.', 'Preview the final customer document.', 'Choose **Send** once.', 'Confirm delivery/activity status and follow up through the customer communication record.', 'If scope changes materially, create the supported revision rather than rewriting the accepted version.'],
    example: 'The property manager’s billing contact receives the estimate link, approves it, and the office converts the approved revision into a job.',
    effects: ['The estimate moves from draft into the sent/approval workflow.', 'The public link records the customer decision.', 'Approval can enable job conversion.'],
    watchFor: ['No valid recipient means the email cannot reach the customer even if status changes.', 'Check spam-sensitive wording and sender configuration.', 'Do not send duplicate copies because the first request appears slow; inspect activity first.'],
  }),
  'converting-estimates': guide({
    summary: 'Conversion creates a job from an approved estimate so accepted customer, location, scope, and line-item data do not need to be re-entered.',
    useWhen: ['The customer approved the proposal.', 'Operational scheduling should begin.', 'The estimate must remain linked to resulting work.'],
    steps: ['Confirm the estimate is the correct approved revision.', 'Choose **Convert to job**.', 'Review the copied customer, service location, billing customer, scope, and lines.', 'Select job type and tenant-defined starting status as required.', 'Schedule visits and assign technicians/crews.', 'Add operational instructions, covered assets, checklist, or parts-source details not known during estimating.'],
    example: 'An approved access-control estimate becomes a job with the same hardware and labor lines; dispatch then schedules installation and assigns the access-control crew.',
    effects: ['A new linked job is created while the estimate remains the approval record.', 'Scheduling and assignment are still required unless explicitly provided.'],
    watchFor: ['Do not convert the wrong revision or convert twice.', 'Recheck current product availability, cost, and service location before dispatch.', 'Estimate approval does not mean field prerequisites are complete.'],
  }),
  'tester-walkthrough': guide({
    summary: 'The tester walkthrough provides an ordered set of product checks and captures feedback tied to the exact feature being tested.',
    useWhen: ['A tester is evaluating a tenant build.', 'Platform staff need repeatable coverage across workflows.', 'Feedback should be tied to a known step.'],
    steps: ['Open the walkthrough widget.', 'Read the current step and perform it using safe test data.', 'Record whether it worked, was confusing, or broke.', 'Add the exact record, action, and error when something fails.', 'Move to the next step or skip when the feature is not applicable.', 'Platform admins review the collected notes and progress.'],
    example: 'For the inventory transfer step, the tester records the source bin, destination bin, item, quantity, and error instead of only writing “transfer broken.”',
    effects: ['Feedback is associated with the walkthrough feature and tester.', 'Skipping does not change product data beyond actions the tester already performed.'],
    watchFor: ['Use non-production customer information.', 'Do not mark a step successful without confirming the resulting record or movement.'],
  }),
  'tester-feedback': guide({
    summary: 'Useful tester feedback explains the starting state, exact action, expected result, actual result, and evidence needed to reproduce the issue.',
    useWhen: ['A workflow fails.', 'The interface is confusing.', 'The result is technically correct but operationally impractical.'],
    steps: ['Name the page and feature.', 'Provide the record identifier and starting state.', 'List the exact clicks or entries.', 'State the expected result.', 'State the actual result and exact error text.', 'Add whether the problem repeats and any screenshot/reference.'],
    example: '“Inventory → Transfer: from Warehouse/A1 to Truck 2/Drawer 1, item CYL-100, quantity 3. Submit returned 422 ‘insufficient stock’; A1 displayed quantity 5. Repeats after refresh.”',
    effects: ['Specific feedback can be reproduced and triaged faster.', 'Feedback itself does not undo test data, so note any cleanup needed.'],
    watchFor: ['“It does not work” is not enough to reproduce.', 'Remove passwords, API secrets, payment data, and customer-sensitive information.'],
  }),
  'acting-as-tenant': guide({
    summary: 'Acting as a tenant gives a platform administrator tenant context for support and testing while preserving platform-level identity and audit boundaries.',
    useWhen: ['Investigating a tenant-specific issue.', 'Verifying onboarding or configuration.', 'Testing permissions and behavior with the tenant’s data context.'],
    steps: ['Select the intended tenant from the acting-as control.', 'Confirm the visible banner before reading or changing records.', 'Use the least invasive action needed to investigate.', 'Record support-relevant findings and avoid changing unrelated configuration.', 'Exit or switch tenant context immediately when finished.'],
    example: 'A platform admin acts as Tenant A to inspect its status mapping, then exits before opening Tenant B’s support request.',
    effects: ['Tenant-scoped API calls and pages use the selected tenant context.', 'Writes may be attributed to the platform actor while affecting tenant data.'],
    watchFor: ['Never assume tenant context from the previous page; read the banner.', 'Do not use acting-as for personal 2FA setup.', 'Without a tenant context, tenant writes should fail rather than guess.'],
  }),
  'admin-portal': guide({
    summary: 'The platform admin area manages tenants, testers, platform inbox activity, and support operations that are not available to tenant users.',
    useWhen: ['Provisioning or reviewing a tenant.', 'Monitoring tester progress.', 'Handling messages routed to the platform inbox.'],
    steps: ['Open the platform-admin menu from the authorized account.', 'Choose Tenants, Testers, Inbox, or the relevant platform function.', 'Confirm whether an action is platform-wide or tenant-scoped.', 'Use acting-as only when tenant context is required.', 'Record sensitive changes and return to platform context when finished.'],
    example: 'Create a tester tenant, verify its owner invitation, then monitor walkthrough notes without granting tenant-owner access to platform administration.',
    effects: ['Platform actions can provision accounts and influence many tenants.', 'Role gates prevent ordinary tenant users from seeing these functions.'],
    watchFor: ['Platform permissions are high impact; do not use shared accounts.', 'Confirm tenant and recipient before provisioning or emailing credentials.'],
  }),
  'tester-email-workflow': guide({
    summary: 'CrewBarn test addresses can route generated product mail into the platform inbox so the team can verify content and delivery without using a tester’s personal mailbox.',
    useWhen: ['Provisioning a controlled tester account.', 'Testing invitations, estimates, reminders, or replies.', 'Reviewing end-to-end platform email behavior.'],
    steps: ['Create the approved `@crewbarn.com` test address using the tenant/tester naming convention.', 'Assign it only to the intended test account or test customer contact.', 'Trigger the email from the real workflow.', 'Open the platform inbox and verify sender, recipient, subject, content, links, and reply routing.', 'Deliver login credentials through the approved separate channel.', 'Remove or retire test addresses when the test is complete.'],
    example: 'Send an estimate to `customer_alice@crewbarn.com`, verify it arrives in the platform inbox, open the approval link, and confirm the resulting estimate activity.',
    effects: ['Messages exercise the actual outbound and inbound routing path.', 'Replies can return to the platform inbox for inspection.'],
    watchFor: ['Do not use test addresses for real customers.', 'Never email passwords in the same message as the username/invitation.', 'Confirm DNS/routing configuration before treating missing mail as an application defect.'],
  }),
}
