export interface SettingsHelpEntry {
  id: string
  group: string
  label: string
  route: string
  description: string
  example: string
  access?: string
}

const viewAccess = 'Your role must be allowed to view this area. Changes require the matching edit or management permission.'
const editAccess = 'Only roles with permission to manage this setting can make changes.'

export const SETTINGS_HELP: SettingsHelpEntry[] = [
  { id: 'automations', group: 'Create & Send', label: 'Automations', route: '/tool-shed/automations', description: 'Connect events, conditions, templates, and actions so routine work happens consistently.', example: 'Send the appointment reminder template before a scheduled visit, or notify dispatch when a job needs a return visit.', access: viewAccess },
  { id: 'templates-forms', group: 'Create & Send', label: 'Templates & Forms', route: '/custom-documents', description: 'Build reusable emails, texts, documents, forms, and customer-facing content.', example: 'Create one cancellation message and attach it to the Canceled status instead of rewriting it for every job.', access: editAccess },
  { id: 'import-data', group: 'Create & Send', label: 'Import Data', route: '/tool-shed/import', description: 'Bring customers, catalog items, and supported accounting data into CrewBarn.', example: 'Upload a customer CSV, map its columns, review validation issues, and import the clean rows.', access: viewAccess },
  { id: 'data-export', group: 'Create & Send', label: 'Data Export', route: '/tool-shed/data-export', description: 'Export tenant data for analysis, migration, backup, or compliance work.', example: 'Export customers or jobs before a large cleanup so the office has a reviewable record.', access: editAccess },

  { id: 'inventory', group: 'Inventory & Assets', label: 'Inventory', route: '/inventory', description: 'Manage where stock lives, quantities, serialized units, transfers, movements, and reconciliations.', example: 'Move ten deadbolts from Warehouse Shelf A to Truck 4 and retain the movement audit trail.', access: viewAccess },
  { id: 'inventory-settings', group: 'Inventory & Assets', label: 'Inventory Settings', route: '/inventory?tab=settings', description: 'Control tenant-wide stock rules, including scanning requirements and who may change inventory behavior.', example: 'Require a technician to scan a product before using it on a job, while allowing an authorized manager to change that rule.', access: editAccess },
  { id: 'service-catalog', group: 'Inventory & Assets', label: 'Service Catalog', route: '/catalog/services', description: 'Maintain labor and service items used on jobs and estimates.', example: 'Create an Annual Inspection service with its default price and tax class.', access: viewAccess },
  { id: 'product-catalog', group: 'Inventory & Assets', label: 'Product Catalog', route: '/catalog/products', description: 'Maintain products, costs, prices, stock behavior, and serial-number tracking.', example: 'Mark an alarm panel as stocked and serial-number tracked before receiving it into inventory.', access: viewAccess },
  { id: 'service-categories', group: 'Inventory & Assets', label: 'Service Categories', route: '/catalog/categories', description: 'Organize service items into the groups staff use in pickers and reports.', example: 'Group Rekey, Lockout, and Master Key services under Locksmith Services.', access: viewAccess },
  { id: 'product-categories', group: 'Inventory & Assets', label: 'Product Categories', route: '/catalog/product-categories', description: 'Organize physical products into a searchable category tree.', example: 'Place cylinders and deadbolts under Door Hardware while keeping access-control boards separate.', access: viewAccess },
  { id: 'customer-assets', group: 'Inventory & Assets', label: 'Customer Assets', route: '/assets', description: 'Track the equipment and objects serviced at customer locations.', example: 'Attach service history, photos, documents, and installed parts to a specific rooftop unit.', access: viewAccess },
  { id: 'asset-access', group: 'Inventory & Assets', label: 'Asset Access Requests', route: '/asset-access-requests', description: 'Review requests made after someone scans an asset QR code without sufficient access.', example: 'Approve a building manager who scanned an extinguisher label and needs its public service record.', access: viewAccess },
  { id: 'asset-types', group: 'Inventory & Assets', label: 'Asset Types', route: '/asset-types', description: 'Define the tenant-specific kinds of equipment your company services.', example: 'Create Fire Extinguisher, Exit Light, and Sprinkler Riser asset types.', access: editAccess },
  { id: 'company-tools', group: 'Inventory & Assets', label: 'Company Tools', route: '/company-assets', description: 'Track company-owned tools and equipment separately from customer assets.', example: 'Assign a combustion analyzer to a technician and preserve its custody history.', access: viewAccess },
  { id: 'vendors', group: 'Inventory & Assets', label: 'Vendors', route: '/vendors', description: 'Maintain suppliers used for products and purchase orders.', example: 'Store the preferred hardware distributor and its ordering contact information.', access: viewAccess },
  { id: 'purchase-orders', group: 'Inventory & Assets', label: 'Purchase Orders', route: '/purchase-orders', description: 'Order products from vendors and receive them into exact inventory bins.', example: 'Receive a partial shipment into Warehouse Receiving and leave the remaining quantity open.', access: viewAccess },
  { id: 'warranties', group: 'Inventory & Assets', label: 'Warranties', route: '/warranties', description: 'Track warranty coverage, claims, expiration, and related jobs or assets.', example: 'Confirm whether a replacement part is still covered before billing the customer.', access: viewAccess },
  { id: 'warranty-settings', group: 'Inventory & Assets', label: 'Warranty Settings', route: '/tool-shed/warranty-settings', description: 'Set tenant warranty claim rules and the expiring-soon warning period.', example: 'Allow one claim per warranty and flag coverage thirty days before expiration.', access: editAccess },

  { id: 'job-types', group: 'Customers & Workflow', label: 'Job Types', route: '/tool-shed/job-types', description: 'Organize jobs by the kind of work being performed. Each type can prefill a starting status, expected duration, and checklist when staff create a job.', example: 'Create an Annual Inspection type with a 90-minute duration, Scheduled as its starting status, and the annual-inspection checklist. New inspection jobs begin with those values already filled in.', access: viewAccess },
  { id: 'job-statuses', group: 'Customers & Workflow', label: 'Job Statuses', route: '/tool-shed/job-statuses', description: 'Define tenant-owned job states, mobile field actions, notification templates, and allowed status flow.', example: 'Map On Site to mobile arrival, require closeout before Complete, and notify the customer when Canceled.', access: editAccess },
  { id: 'tags', group: 'Customers & Workflow', label: 'Tags', route: '/tool-shed/tags', description: 'Create flexible labels for filtering and organizing records.', example: 'Tag customers as Property Manager or jobs as After Hours without changing their core type.', access: viewAccess },
  { id: 'customer-types', group: 'Customers & Workflow', label: 'Customer Types', route: '/tool-shed/customer-types', description: 'Define customer classifications used by your tenant.', example: 'Separate Residential, Commercial, Government, and Property Management accounts.', access: viewAccess },
  { id: 'service-locations', group: 'Customers & Workflow', label: 'Service Locations', route: '/tool-shed/service-locations', description: 'Review and manage the physical addresses where customer work occurs.', example: 'Keep a corporate billing customer while adding each branch as its own service location.', access: viewAccess },
  { id: 'territories', group: 'Customers & Workflow', label: 'Territories', route: '/tool-shed/territories', description: 'Group service areas for dispatching, ownership, and reporting.', example: 'Assign north-county ZIP codes to one dispatch territory and coastal ZIP codes to another.', access: viewAccess },
  { id: 'custom-fields', group: 'Customers & Workflow', label: 'Custom Fields', route: '/tool-shed/custom-fields', description: 'Add tenant-specific structured fields to supported records and forms.', example: 'Require a Gate Code field on service locations or an Inspection Number on jobs.', access: editAccess },

  { id: 'staff-crews', group: 'Team & Access', label: 'Staff & Crews', route: '/tool-shed/staff', description: 'Invite staff, organize crews, assign roles, and manage field access.', example: 'Invite a technician to the mobile app and place them on the South Crew.', access: 'Staff visibility and changes follow staff and role permissions.' },
  { id: 'hiring', group: 'Team & Access', label: 'Hiring', route: '/tool-shed/hiring', description: 'Post openings with your own requirements and application questions; review applicants and hire them straight into staff onboarding.', example: 'Switch hiring on, post "Automotive Locksmith Technician" for Melbourne, FL, and job seekers find it on the CrewBarn job board.', access: 'Follows staff permissions: staff.view to see applicants, staff.edit to post and hire.' },
  { id: 'subcontractors', group: 'Team & Access', label: 'Subcontractors', route: '/tool-shed/subcontractors', description: 'Maintain outside workers or companies used on jobs.', example: 'Assign a licensed subcontractor to a specialty inspection while retaining the job record.', access: viewAccess },
  { id: 'roles-permissions', group: 'Team & Access', label: 'Roles & Permissions', route: '/tool-shed/roles', description: 'Control which functions each tenant role may view or change.', example: 'Allow dispatchers to edit schedules but reserve payment and inventory settings for managers.', access: 'Only authorized role managers should change permissions. Owners retain full control.' },
  { id: 'time-off', group: 'Team & Access', label: 'Time Off', route: '/tool-shed/time-off', description: 'Record staff unavailability so scheduling reflects who can actually work.', example: 'Block a technician from dispatch assignments during approved vacation.', access: viewAccess },
  { id: 'security', group: 'Team & Access', label: 'Security & 2FA', route: '/tool-shed/security', description: 'Manage personal two-factor authentication and the tenant security policy.', example: 'Require 2FA for tenant staff while letting each person enroll their own authenticator.', access: 'Personal enrollment belongs to the signed-in user; tenant policy changes require authorized settings access.' },
  { id: 'delete-permissions', group: 'Team & Access', label: 'Delete Permissions', route: '/tool-shed/preferences#delete-permissions', description: 'Choose who can delete records and what they must do to confirm it.', example: 'Let the owner delete without retyping a password while staff still have to.', access: 'Anyone with settings access can read the rules; only the company owner can change them.' },
  { id: 'encryption', group: 'Team & Access', label: 'Data Encryption (BYOK)', route: '/tool-shed/encryption', description: 'Configure tenant-managed encryption keys for supported sensitive data.', example: 'Connect a customer-owned key when contract requirements call for tenant-controlled encryption.', access: editAccess },
  { id: 'company-files', group: 'Team & Access', label: 'Company Files', route: '/tool-shed/company-files', description: 'Store secure internal files with permission-controlled access.', example: 'Keep licenses or internal procedures available only to approved office roles.', access: 'Listing, viewing, uploading, and managing secure files use separate permissions.' },

  { id: 'integrations', group: 'Connections', label: 'Integrations', route: '/tool-shed/integrations', description: 'Review available connections and open the correct setup area for each service.', example: 'Start from here when deciding whether maps, communications, accounting, or another provider needs configuration.', access: viewAccess },
  { id: 'communication', group: 'Connections', label: 'Phone, SMS & Email', route: '/tool-shed/communication', description: 'Choose either CrewBarn Hosted or BYO Twilio for mobile in-app calling, then optionally add the tenant-owned Net2Phone account for office calls, customer texting, recordings, and webhooks. Email can use CrewBarn fallback delivery or the tenant BYO Resend/SMTP setup.', example: 'Select CrewBarn Hosted Twilio for tracked technician calls and enable BYO Net2Phone as the office add-on. For email, use From address for the sender customers see only when the tenant provider or verified domain authorizes it. With CrewBarn fallback, CrewBarn remains the sender and Reply-to sends customer replies to the tenant while preserving the CrewBarn conversation thread.', access: editAccess },
  { id: 'cbi-ai', group: 'Connections', label: 'CBI AI Settings', route: '/tool-shed/ai', description: 'Choose the AI provider, control allowed tasks, and manage how CBI uses current tenant records plus approved business memory.', example: 'Correct a wrong part guess with the verified vehicle context, approve the memory, and let later Intake suggestions combine that correction with current catalog and stock data.', access: editAccess },
  { id: 'storage-maps', group: 'Connections', label: 'Storage & Maps', route: '/tool-shed/storage-maps', description: 'Configure tenant-owned file storage and Google Maps behavior.', example: 'Use the server-restricted Maps key for server requests and the approved browser key for map display.', access: editAccess },
  { id: 'gps-devices', group: 'Connections', label: 'GPS Devices', route: '/tool-shed/gps', description: 'Register and manage supported vehicle or field GPS devices.', example: 'Activate a tracker for Truck 4 so dispatch can see its current position.', access: viewAccess },
  { id: 'api-tokens', group: 'Connections', label: 'API Tokens', route: '/tool-shed/api-tokens', description: 'Issue revocable credentials for approved external systems.', example: 'Create a dedicated token for an accounting integration instead of sharing a user login.', access: editAccess },
  { id: 'self-hosted', group: 'Connections', label: 'Self-hosted Console', route: '/tool-shed/self-hosted', description: 'Run the open-source CrewBarn console on your own domain. Activate each domain with a token (shown once); the token\'s level follows your subscription — free is read-only — and rotates monthly. Data, logins and provider keys stay on CrewBarn.', example: 'Activate sub.yourcompany.com or www.yourcompany.com, paste the token into the console\'s setup page, and your team signs in there with their normal logins.', access: editAccess },
  { id: 'api-endpoints', group: 'Connections', label: 'API Endpoint Guide', route: '/tool-shed/api-endpoints', description: 'Browse the tenant-safe business API and follow simple examples for reaching related data.', example: 'List customers, copy a customer ID, then retrieve its contacts, service locations, documents, or outstanding invoices.', access: viewAccess },
  { id: 'webhooks', group: 'Connections', label: 'Webhooks', route: '/tool-shed/webhooks', description: 'Send signed event notifications from CrewBarn to outside systems.', example: 'Notify an external reporting service when a job changes status or a payment is recorded.', access: editAccess },
  { id: 'connected-apps', group: 'Connections', label: 'Connected Apps', route: '/tool-shed/connected-apps', description: 'Review active app connections and disconnect access that is no longer needed.', example: 'Remove an old accounting connection after confirming the replacement is live.', access: editAccess },
  { id: 'marketplace', group: 'Connections', label: 'Marketplace Listing', route: '/tool-shed/marketplace', description: 'Control whether and how your company appears in the CrewBarn marketplace.', example: 'Publish a fire-safety listing for selected ZIP codes with a clear customer-facing description.', access: editAccess },
  { id: 'partner-connections', group: 'Connections', label: 'Partner Connections', route: '/tool-shed/partner-connections', description: 'Manage approved business-to-business tenant connections.', example: 'Connect with a trusted partner for referred or shared work while keeping tenant records separate.', access: editAccess },

  { id: 'company-info', group: 'Business Controls', label: 'Company Info', route: '/tool-shed/company-info', description: 'Maintain the legal, contact, address, and operational identity used throughout CrewBarn.', example: 'Update the phone number and address that appear on customer documents.', access: editAccess },
  { id: 'brand-logo', group: 'Business Controls', label: 'Brand & Logo', route: '/tool-shed/brand', description: 'Set the logo and brand colors used in customer-facing documents and experiences.', example: 'Upload a transparent logo and choose the accent color used on estimates and the portal.', access: editAccess },
  { id: 'website-builder', group: 'Business Controls', label: 'Website Builder', route: '/tool-shed/website', description: 'Create, preview, connect, and publish the tenant website.', example: 'Generate service-page copy, review the mobile preview, connect a domain, and publish.', access: editAccess },
  { id: 'shop-rules', group: 'Business Controls', label: 'Shop Rules', route: '/tool-shed/preferences', description: 'Set numbering, field workflow, intake, reminders, and GPS behavior for the tenant.', example: 'Require field photos at closeout and choose when appointment reminders are sent.', access: editAccess },
  { id: 'pricing-discounts', group: 'Business Controls', label: 'Pricing & Discounts', route: '/tool-shed/pricing', description: 'Configure pricing behavior and the discounts staff may apply.', example: 'Create an approved senior discount instead of allowing arbitrary line-item reductions.', access: viewAccess },
  { id: 'cost-model', group: 'Business Controls', label: 'Cost Model', route: '/tool-shed/cost-model', description: 'Define labor and overhead assumptions used for profitability reporting.', example: 'Include loaded technician labor cost so job margin reflects more than product cost.', access: 'Revenue visibility is required because this area exposes business cost information.' },
  { id: 'tax-classes-setting', group: 'Business Controls', label: 'Tax Classes', route: '/catalog/tax-classes', description: 'Define reusable tax rates and components for catalog items and transactions.', example: 'Combine state and local components into one tax class assigned to taxable products.', access: viewAccess },
  { id: 'payment-terms', group: 'Business Controls', label: 'Payment Terms', route: '/tool-shed/payment-terms', description: 'Define when invoices are due and the labels customers see.', example: 'Create Due on Receipt and Net 30 terms, then assign the appropriate default.', access: viewAccess },
  { id: 'payment-types', group: 'Business Controls', label: 'Payment Types', route: '/tool-shed/payment-types', description: 'Control built-in and custom ways staff can record customer payments.', example: 'Add Financing as a custom type while retaining Cash, Check, and Card.', access: editAccess },
  { id: 'card-payments', group: 'Business Controls', label: 'Payments', route: '/tool-shed/payments', description: 'Card processor (Stripe or GoDaddy Payments), bank transfers customers can pay from the portal, and the watched bank account that matches them.', example: 'Connect GoDaddy Payments or Stripe, turn on Pay by bank transfer, connect your business checking so transfers match to invoices.', access: editAccess },
  { id: 'customer-app', group: 'Business Controls', label: 'Customer App', route: '/tool-shed/customer-app', description: 'Your own branded app for the Play Store and App Store: name it, upload an icon, pick the features, pay once, build, then list it from your own developer accounts.', example: 'Build "Key-En-Lock" with request service, invoices and messages; customers who install it see only your company.', access: editAccess },
  { id: 'cloudflare', group: 'Business Controls', label: 'Connect Cloudflare', route: '/tool-shed/cloudflare', description: 'Connect supported Cloudflare services used by tenant web or domain features.', example: 'Authorize the correct account before attaching a website domain.', access: editAccess },
  { id: 'modules', group: 'Business Controls', label: 'Modules', route: '/tool-shed/modules', description: 'Show or hide optional product modules for the tenant.', example: 'Hide purchasing for a service-only tenant while keeping jobs, customers, and invoicing available.', access: editAccess },
  { id: 'app-layout', group: 'Business Controls', label: 'App Layout', route: '/tool-shed/appearance', description: 'Choose navigation style, density, page width, and default views.', example: 'Use a compact office layout for dispatchers and a field-oriented layout for technicians.', access: viewAccess },
  { id: 'onboarding', group: 'Business Controls', label: 'Onboarding', route: '/onboarding', description: 'Complete the guided tenant setup and seed practical starting defaults.', example: 'Add company details, staff, statuses, templates, and integrations before going live.', access: viewAccess },
  { id: 'subscription', group: 'Business Controls', label: 'Subscription', route: '/tool-shed/subscription', description: 'Your CrewBarn plan: $150/month for the company and one admin, then $35/month for each additional person who signs in. See seats purchased vs in use, add or remove seats, and manage the card and invoices on the billing portal.', example: 'Hire a fourth tech: add a seat here, then invite them under Staff. Disable someone and their seat frees up right away.', access: editAccess },
  { id: 'usage-limits', group: 'Business Controls', label: 'Usage & Limits', route: '/tool-shed/usage', description: 'Review current tenant consumption and plan limits.', example: 'Check storage or user usage before adding a large import or another staff member.', access: viewAccess },
  { id: 'audit-log', group: 'Business Controls', label: 'Audit Log', route: '/tool-shed/audit-log', description: 'Review who changed important tenant data and when.', example: 'Confirm which user changed a permission or business setting during an investigation.', access: viewAccess },
  { id: 'franchise-access', group: 'Business Controls', label: 'Franchise Access', route: '/franchise-support', description: 'Control franchisor support access for a franchise tenant.', example: 'Temporarily allow franchisor support to review configuration while retaining a clear access boundary.', access: editAccess },
]

export const SETTINGS_HELP_GROUPS = [
  'Create & Send',
  'Inventory & Assets',
  'Customers & Workflow',
  'Team & Access',
  'Connections',
  'Business Controls',
] as const

export function settingsHelpTopicId(id: string): string {
  return `settings-${id}`
}

export function findSettingsHelpByRoute(path: string): SettingsHelpEntry | undefined {
  const exact = SETTINGS_HELP.find((entry) => entry.route === path)
  if (exact) return exact

  const pathname = path.split(/[?#]/, 1)[0]
  return SETTINGS_HELP.find((entry) => entry.route.split(/[?#]/, 1)[0] === pathname)
}

export function settingsHelpForRoute(route: string): SettingsHelpEntry | undefined {
  return SETTINGS_HELP.find((entry) => entry.route === route)
}
