/**
 * AssetPhoto types matching AssetPhotoResource on backend.
 *
 * SLICE-4: photo upload pipeline.
 *
 * URLs are public-readable via images.crewbarn.com (Cloudflare CDN backed by R2).
 * Three sizes generated by the backend pipeline:
 *   - thumb_url:  300x300 max, used in galleries
 *   - medium_url: 800x800 max, used in detail views
 *   - full_url:   original dimensions, used for download/lightbox
 *
 * Backend: app/Http/Resources/AssetPhotoResource.php
 */

import type { PaginatedResponse, ResourceResponse } from "@/types/api"
export type { PaginatedResponse, ResourceResponse }

export interface AssetPhoto {
  id: string
  asset_id: string
  thumb_url: string | null
  medium_url: string | null
  full_url: string | null
  original_filename: string | null
  mime_type: string | null
  size_bytes: number | null
  caption: string | null
  sort_order: number
  uploaded_by_account_id: string | null
  created_at: string | null
  updated_at: string | null
}
